os: linux
language: python
addons:
  apt:
    packages:
      - lua5.2
      - liblua5.2-dev
cache: pip
install:
  - export PKG_CONFIG_PATH="$(python-config --prefix)/lib/pkgconfig:$PKG_CONFIG_PATH"
  - echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
  # The above two statements can be removed when/if https://github.com/travis-ci/travis-ci/issues/8217 is fixed
  - pip install -U pip tox
matrix:
  include:
    - stage: build
      name: "Functional Tests"
      language: shell
      dist: xenial
      addons:
        apt:
          # Upgrade Docker to the latest (see https://docs.travis-ci.com/user/docker/)
          sources:
            - docker-xenial
          packages:
            - docker-ce
      services:
        - docker
      install:
        - docker --version
        - docker-compose --version
      script:
        - ./functional.sh verbose
    - stage: build
      name: "Unit Tests: Python 2.7 with Attrs 18 and 19"
      python: "2.7"
      script:
        - tox -e py27-attrs18,py27-flake8,py27-coverage
    - stage: build
      name: "Unit Tests: Python 3.5 with and without PyInotify; Pytest 5.1 and 5.3"
      python: "3.5"
      script:
        - tox -e py35,py35-pyinotify,py35-pytest51,py35-pytest53,coverage
    - stage: build
      name: "Unit Tests: Python 3.7 with Attrs 18 and 19; PyTest 4.6 and 5.3"
      python: "3.7"
      script:
        - tox -e py37-attrs18,py37-pytest46,py37-flake8,coverage,py37-mypy
      dist: xenial
    - stage: build
      name: "Unit Tests: Python 3.8 with Currint 1.6 and 2.0"
      python: "3.8"
      script:
        - tox -e py38,py38-currint16,coverage,py38-mypy
      dist: xenial
    - stage: deploy
      python: "3.7"
      script: skip
      install:
        - pip install -U pip setuptools pyopenssl
      deploy:
        provider: pypi
        username: eventbrite
        password:
          secure: NEMxpJWYikoIHVogbkJq45mcuXgbPBmjmSHrDxOJLbkYtGJpIMZjCe1VXtDIxyZks9rk6DztVJO/5OWb6uBTyDCkwqCGqMGQLoAPw0qNbbs9PibV/0pA5Z5MdZKHueOxydFP6jaZVdMm8or3jzaidbZevo/y4nhrvjjLX/Hyn6BEHJOai3wHQEf4OUAbkS7W/7ga1oBLgNypWmVPKUqXkszON8iVqzdrkhx3pJcWgJUIngb0GYr1WkzwFrKIN1SGb+K2hmYwWxdaRzqDs5YQdmWoywGeB0Lj0ho+yScEH5MdAYyfoUnRnftmWTZW38SskAAoUZsDIoqvPa3uA1vboo8/CJUwdu4j3Ta+BmZQQp3SRVXkZaHaaMLPnkmmIC+jEOvfCVLRQ9u2XE2tB86Yd0FGJM7JXGaNh0mGRZmbZamml5j3RMq2wCRS73STlZyaa9QOBeCBBoaKZk0orbcvZn2rfUMOdn6CmjycqflhscNsTFimClzhGDsjLKr67upsr9BDVAzN6Kh2Pcy9ka0qlu4iVJo5u7wo/LtfEvlV8tE8Qoqub0VnwLBJSFPILF/HONYrJ1Ux7avmJwU6Drn5UaC434VegJoXPrViXh2j+Z6+6HsnrCNoWlEsrhbkTMhSg/niyb/bVUgvvvWdpEk44soYKZp9Et2Qvbubq7ddg2Y=
        distributions: "sdist bdist_wheel"
        on:
          tags: true
stages:
  - build
  - name: deploy
    if: tag =~ ^[0-9]+\.[0-9]+\.[0-9]+
