FROM python:3.7-stretch

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        mysql-client \
        default-libmysqlclient-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY LICENSE NOTICE README.rst setup.cfg setup.py /srv/pysoa/
COPY pysoa/__init__.py pysoa/version.py /srv/pysoa/pysoa/
RUN pip install -e /srv/pysoa
RUN pip install coverage
COPY pysoa /srv/pysoa/pysoa/
RUN pip install -e /srv/pysoa

RUN mkdir -p /srv/run
WORKDIR /srv/run

RUN echo '#!/bin/sh\n\
set -e\n\
\n\
if [ -f "/usr/local/bin/pysoa-startup-processes.sh" ]\n\
then\n\
    . /usr/local/bin/pysoa-startup-processes.sh\n\
fi\n\
\n\
if [ "${DISABLE_COVERAGE}" = "true" ]\n\
then\n\
    set -x\n\
    exec "$@"\n\
else\n\
    set -x\n\
    # For relaunches, we use --append so that it does not erase previous processes\' coverage data files\n\
    export PYSOA_RELOADER_WRAPPER_BIN="coverage run --append --concurrency=multiprocessing"\n\
    exec coverage run --concurrency=multiprocessing "$@"\n\
fi\n\
' > /usr/local/bin/pysoa-entrypoint.sh
RUN chmod +x /usr/local/bin/pysoa-entrypoint.sh

RUN echo '#!/bin/sh\n\
set -ex\n\
echo $2 > $1\n\
' > /usr/local/bin/simple_write.sh
RUN chmod +x /usr/local/bin/simple_write.sh

ENTRYPOINT ["pysoa-entrypoint.sh"]
