# Common ASGI constants for discovery and transport classes
ASGI_CHANNEL_TYPE_LOCAL = u'local'
ASGI_CHANNEL_TYPE_REDIS = u'redis'
ASGI_CHANNEL_TYPE_REDIS_SENTINEL = u'redis_sentinel'

ASGI_CHANNEL_TYPES_LOCAL = (
    ASGI_CHANNEL_TYPE_LOCAL,
)

ASGI_CHANNEL_TYPES_REDIS = (
    ASGI_CHANNEL_TYPE_REDIS,
    ASGI_CHANNEL_TYPE_REDIS_SENTINEL,
)

ASGI_CHANNEL_TYPES = ASGI_CHANNEL_TYPES_LOCAL + ASGI_CHANNEL_TYPES_REDIS
