from __future__ import unicode_literals

# Common ASGI constants for discovery and transport classes
ASGI_CHANNEL_TYPE_LOCAL = 'local'
ASGI_CHANNEL_TYPE_REDIS = 'redis'
ASGI_CHANNEL_TYPE_REDIS_SENTINEL = 'redis_sentinel'

ASGI_CHANNEL_TYPES_LOCAL = (
    ASGI_CHANNEL_TYPE_LOCAL,
)

ASGI_CHANNEL_TYPES_REDIS = (
    ASGI_CHANNEL_TYPE_REDIS,
    ASGI_CHANNEL_TYPE_REDIS_SENTINEL,
)

ASGI_CHANNEL_TYPES = ASGI_CHANNEL_TYPES_LOCAL + ASGI_CHANNEL_TYPES_REDIS
